CREATE TABLE "cat_care"."bloodwork_records" (
	"id" uuid PRIMARY KEY NOT NULL,
	"cat_id" uuid NOT NULL,
	"recorded_by" uuid NOT NULL,
	"recorded_at" timestamp with time zone NOT NULL,
	"status" text NOT NULL,
	"glu" double precision,
	"crea" double precision,
	"bun" double precision,
	"bun_crea" double precision,
	"tp" double precision,
	"alb" double precision,
	"glob" double precision,
	"alb_glob" double precision,
	"alt" double precision,
	"alkp" double precision,
	"fpl" double precision,
	"na" double precision,
	"k" double precision,
	"na_k" double precision,
	"cl" double precision,
	"osm_calc" double precision,
	"tt4" double precision,
	"wbc" double precision,
	"lym" double precision,
	"mono" double precision,
	"gran" double precision,
	"lym_percent" double precision,
	"mon_percent" double precision,
	"gra_percent" double precision,
	"hgb" double precision,
	"hct" double precision,
	"rbc" double precision,
	"mcv" double precision,
	"mch" double precision,
	"mchc" double precision,
	"rdw_percent" double precision,
	"rdwa" double precision,
	"plt" double precision,
	"mpv" double precision,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cat_care"."bloodwork_records" ADD CONSTRAINT "bloodwork_records_cat_id_cats_id_fk" FOREIGN KEY ("cat_id") REFERENCES "cat_care"."cats"("id") ON DELETE cascade ON UPDATE no action;